// UI
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_TOAST_OPEN = "SET_TOAST_OPEN";
export const RESET_TOAST = "RESET_TOAST";
export const SET_VIEWPORT = "SET_VIEWPORT";
export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAIL = "AUTH_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
