// UI
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_TOAST_OPEN = "SET_TOAST_OPEN";
export const RESET_TOAST = "RESET_TOAST";
export const SET_VIEWPORT = "SET_VIEWPORT";
export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";
